### ISSUE TITLE
Thread safety in the pool

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [usercode/AsyncKeyLock#3]
Is the pool lacking thread safety purposely? I think there's potential for some race conditions

**Comment by usercode** [comment]
Yeah, the pool is not threadsafe. But it is used only in a lock scope.

**Comment by MarkCiliaVincenti** [comment]
Well, two threads with different keys could end up using the same item from the pool. And then what could happen is that the same object is then re-added twice to the same pool.

**Comment by usercode** [comment]
> Well, two threads with different keys could end up using the same item from the pool. 

No, the methods AsyncLock<TKey>.ReaderLockAsync and AsyncLock<TKey>.WriterLockAsync use a lock.

> And then what could happen is that the same object is then re-added twice to the same pool.

No, after the last lock is released, the AsyncLock object switchs to idle state and fires the release event which adds the object to the pool. This happens just one time.

**Comment by MarkCiliaVincenti** [comment]
I'm not sure I understand.

Let's say two threads at the same time try to access the writerlockasync, one for key ABC and another for key DEF.

So 2 threads could be inside GetOrCreate inside Pool.cs, no?

**Comment by MarkCiliaVincenti** [comment]
Ah I get it, it's locked so there can only be 1 thread inside GetOrCreate.
